# Generated by Django 5.0.6 on 2024-05-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idlibro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/libros/', verbose_name='Imagen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
